# Generated by Django 2.2 on 2019-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('user_class',
                 models.TextField(choices=[('S', '发起者'), ('A', '参与者')])),
            ],
        ),
    ]
