# Generated by Django 2.2 on 2019-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='delete_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
