# Generated by Django 2.2 on 2019-04-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='number_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='number',
            field=models.IntegerField(),
        ),
    ]
